### ISSUE TITLE
User can search for anime.  

### ISSUE THREAD

**Issue by jonathantrang** [jonathantrang/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can search for anime.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a responsive search bar that allows users to search for anime that is specific to their input or closely related to the input.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="551" alt="image" src="https://user-images.githubusercontent.com/96746037/157514237-34edb705-bf80-4e53-8384-e78dab8c4133.png">

<img width="834" alt="image" src="https://user-images.githubusercontent.com/96746037/157514392-db55a5db-4326-4e92-a8d1-0ca979a5109a.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Add a `<div>` for the header.
- [ ] Add a `<div>` for navigation bar.
- [ ] Add a `<div[data-view="search-bar"]>` to the HTML.
- [ ] Add a input for creating a search to the `<div[data-view="search-bar"]>`
- [ ] Add a button for creating a search to the `<div[data-view="search-bar"]>`
- [ ] Listen for `'submit'` events on the search input and button
- [ ] Listen for `'click'` events on the header and nav bar
- [ ] Input on the search will reset if click events occur
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
